### ISSUE TITLE
Update hast-util-raw

### ISSUE THREAD

**Issue by radarfox** [rehypejs/rehype-raw#23]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Please, update `hast-util-raw` dependency to v8 and thus `parse5` to v7. Otherwise, two `parse5` dependencies will be installed in my project. The other coming from `hast-util-from-html@1.0.2` (currently the latest version).

### Solution

`npm update hast-util-raw@^8.0.0`

### Alternatives

None

**Comment by wooorm** [comment]
Hi!

Everything will be updated.
Updating everything takes months.
It’s not beneficial to have some issues about some updates open, so I’ll close this.
I’ll get to it!
