### ISSUE TITLE
Typescript error while using rehype-raw with react-markdown

### ISSUE THREAD

**Issue by slumbering** [rehypejs/rehype-raw#25]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"react-markdown": "^8.0.7", "rehype-raw": "^7.0.0"

### Steps to reproduce

1 - Create a new react project (NextJS project in my case).

```shell
npx create-next-app@latest
```

2 - Install React markdown

```shell
npm install react-markdown
```

3- Install rehype-raw

```shell
npm install rehype-raw
```

Now if you try to use rehype raw with react markdown, you should get the following error:
![Capture d’écran 2023-09-04 à 10 14 46](https://github.com/rehypejs/rehype-raw/assets/1186424/bc3e27e8-86c7-47a9-83bc-9649f6946e3d)

Text version:
```
Type '(options?: Options | null | undefined) => (tree: Root, file: VFile) => Root' is not assignable to type 'Pluggable<any[]>'.
  Type '(options?: Options | null | undefined) => (tree: Root, file: VFile) => Root' is not assignable to type 'Plugin<any[], any, any>'.
    Type '(tree: Root, file: VFile) => Root' is not assignable to type 'void | Transformer<any, any>'.
      Type '(tree: Root, file: VFile) => Root' is not assignable to type 'Transformer<any, any>'.
        Types of parameters 'file' and 'file' are incompatible.
          Type 'import("/private/tmp/my-app/node_modules/vfile/lib/index").VFile' is not assignable to type 'import("/private/tmp/my-app/node_modules/hast-util-raw/node_modules/vfile/lib/index").VFile'.
            Types of property 'messages' are incompatible.
              Type 'import("/private/tmp/my-app/node_modules/vfile-message/lib/index").VFileMessage[]' is not assignable to type 'import("/private/tmp/my-app/node_modules/hast-util-raw/node_modules/vfile-message/lib/index").VFileMessage[]'.
                Type 'VFileMessage' is missing the following properties from type 'VFileMessage': ancestors, placets(2322)
```

### Expected behavior

After updating rehype-raw from 6.1.1 to 7, the plugin should work seamlessly with react-markdown and not generate any TypeScript errors. It should be fully compatible right out of the box.

### Actual behavior

I'm getting a typescript error after updating rehype-raw from 6.1.1 to 7

### Runtime

Node v16

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
https://github.com/remarkjs/react-markdown/issues/765
