### ISSUE TITLE
<video> tags not being processed correctly

### ISSUE THREAD

**Issue by wsprouid798** [rehypejs/rehype-raw#26]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"rehype-raw": "^6.1.1"

### Steps to reproduce

I am using the following code:

```
<figure>
  <video width="100%" height="100%" controls >
    <source src="example.mp4" type="video/mp4" />
    <p>
      Your browser doesn't support HTML video. Here is a
      <a href="example.mp4">link to the video</a> instead.
    </p>
  </video>
  <figcaption class="figure-caption">example.mp4</figcaption>
</figure>
```

on a .md file in NextJS (Node v20, NPM 9).

### Expected behavior

A video should be rendered on the resulting HTML page.

### Actual behavior

A video is not rendered and upon closer inspection, an img tag is being spat out instead.

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

Linux

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
try [7.0.0](https://github.com/rehypejs/rehype-raw/releases/tag/7.0.0), it contains https://github.com/syntax-tree/hast-util-raw/commit/e66705ab1b64f867760638544c0e8488953df766.

**Comment by wsprouid798** [comment]
Upgraded.
I put this:
```
<video width="100%" height="auto" controls>
  <source src="/example.mp4" type="video/mp4" />
  Your browser does not support the video tag.
</video>
```
This is output in dev tools:
![image](https://github.com/rehypejs/rehype-raw/assets/136234092/446be525-8e44-4b13-b656-f18e1d7181c2)

Paths are correct and no error in console. Interestingly, img tags work fine. This only has to do with video. Video encoding has been checked and it loads fine directly in browser.

**Comment by Murderlon** [comment]
Here you can see it working as expected: https://stackblitz.com/edit/github-aeyswk?file=src%2Fmain.ts

This is probably an issue with your config, for which there is not enough information to help.

**Comment by wsprouid798** [comment]
Indeed, it's been my config.

I have video showing now with the help of the docs and your example.

Thanks and closing.
