### ISSUE TITLE
Package 'devop'

### ISSUE THREAD

**Issue by GABuryan** [rehypejs/rehype-raw#29]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Hello, lovely library. But is it possible to design a devop package so that it is understood by all collectors, i.e. with index.js, as in the other packages.

We have to stay on version 6.1.1, where it is not used.

### Solution

Arrange it in a standard way

### Alternatives

-

**Comment by wooorm** [comment]
"devlop" works.
This project works.
Your tools don't work.
Configure your broken tools.
Ask a question with information if you don't know your tools.

**Comment by GABuryan** [comment]
Thank's for answer. My tools (webpack) by default search index.js with export objects. In devlop only default.js. Ok, I will think about how to configure it. The difficulty is that he is inside the CRA.

**Comment by remcohaszing** [comment]
IIRC CRA uses the outdated Webpack 4. Webpack 5 supports this just fine. I strongly recommend migrating away from CRA.

You could switch from CRA to Webpack 5. This seems like a logical choice, but it requires some additional configuration for example to support JSX.

Personally I recommend switching to [Vite](https://vitejs.dev). It’s generally faster, simpler, and you might not even need any configuration at all.

**Comment by GABuryan** [comment]
> IIRC CRA uses the outdated Webpack 4. Webpack 5 supports this just fine. I strongly recommend migrating away from CRA.
> 
> You could switch from CRA to Webpack 5. This seems like a logical choice, but it requires some additional configuration for example to support JSX.
> 
> Personally I recommend switching to [Vite](https://vitejs.dev). It’s generally faster, simpler, and you might not even need any configuration at all.

Thank`s for recomendation.
