### ISSUE TITLE
Unknown tags which are self closing do not close

### ISSUE THREAD

**Issue by Specy** [rehypejs/rehype-raw#30]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.0.0

### Steps to reproduce

I'm using this lib as a sort of MDX to have a realtime markdown editor with some custom components, i'm using the react-markdown lib, and adding custom components under the `components` propriety.
When dealing with known tags, like `<a />` everything seems to work properly, but when using custom tags, for example a `<Pdf src="..."/>`, it seems like the tag never closes. I've read #16 and #8 made sure there were a new line between the component and the rest, this is the source: 
```md
test (shown)

<Pdf src="somepdf.pdf" />

test 123 (not shown, as the pdf component has no children, but it is being sent as a child to Pdf)
```
To make it work i need to manually close the tag `<Pdf src="..." ></Pdf>`.
Is this expected behaviour? If so, is there a workaround?

If it could be useful, this is my code:

```tsx
<ReactMarkdown
        remarkPlugins={[
            remarkGfm,
            remarkMath,
        ]}
        rehypePlugins={[
                [rehypeKatex, {output: 'htmlAndMathml'}],
                rehypeRaw,
            ]
        }
        components={{
            //hidden rest of components
            pdf: withPropsValidator(MD_CUSTOM_COMPONENTS.pdf, ({props, children}) => {
                return <PDFRenderer
                    src={props.src}
                    style={{
                        width: props.width,
                        minHeight: props.minheight,
                        height: props.height,
                    }}
                    allowOpen={props.allowopen}
                    allowToolbar={props.allowtoolbar}
                    allowResize={props.allowresize}
                />
            }),
        }}
    >
        {markdown}
    </ReactMarkdown>;
```

### Expected behavior

I expect the custom <pdf> tag to close, leading to further source to be parsed on it's own instead of being a child of the self closing tag

### Actual behavior

The custom self closing tag doesn't close, making all the next items as children of this tag

### Runtime

Node v17

### Package manager

npm 8

### OS

Windows

### Build and bundle tools

Next.js

**Comment by ChristianMurphy** [comment]
Welcome @Specy! 👋 
Sorry you ran into confusion.

HTML does not have self closing tags.
It has void elements, void elements are only well known tags that come from this list https://developer.mozilla.org/en-US/docs/Glossary/Void_element

`<pfd>` is not a valid void element (not valid HTML at all) so it does not self close.
Add a closing tag, or if you want JSX support, consider using MDX https://mdxjs.com/
