### ISSUE TITLE
Revert HAST to String

### ISSUE THREAD

**Issue by gustavomm19** [rehypejs/rehype-raw#31]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Is there a way to make the convertion optional for some components? I have a custom component in the Markdown Parser from react-markdown and I need it to keep its children always as a string, but if there is html content inside that content, that content gets parsed as nodes. Is there a way to prevent that? I need the plugin to make that convertion in other components but NOT in this one. Here is an example of my code

```
<ReactMarkdown
        remarkPlugins={[remarkGfm, remarkGemoji, remarkMath]}
        rehypePlugins={[rehypeRaw, rehypeKatex]}
        components={{
          codeviewer: CodeViewerComponent,
        }}
      >
        {preParsedContent}
      </ReactMarkdown>
```

### Solution

Maybe if there were a function to unparse the children of a component

### Alternatives

Or a list of components to just receive the children unparsed

**Comment by JounQin** [comment]
Welcome, @gustavomm19 

Maybe you mean to use https://github.com/rehypejs/rehype/tree/main/packages/rehype-stringify

**Comment by wooorm** [comment]
I don’t think you’re working with html. HTML does not have that at all. It looks like you want jsx.

that’s not this project. You are likely looking for MDX

**Comment by gustavomm19** [comment]
I solved this problem by using the position indexes of the node that comes as a prop, to extract the parts that I needed from the original content before it is parsed by the markdown parser

**Comment by wooorm** [comment]
I think you’re going in the wrong direction; there might be dragons, but good luck.
