### ISSUE TITLE
Issue when mixing html with markdown

### ISSUE THREAD

**Issue by MikeRenwick-ICG** [rehypejs/rehype-raw#32]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

rehype-raw 7.0.0

### Link to runnable example

https://codesandbox.io/s/rehype-raw-issue-yvcsts?file=/src/app.tsx

### Steps to reproduce

const markdownSource = `
**When using rehype-raw with React-Markdown**

<div class="note"></div>
[This link doesn't work when a div is present](abc123) Nor does *markdown that follows*

until a double new line *Hooray* and <strong>Hurrah</strong>!
at which point 
[This link works again](abc123)

It's almost as though it terminates treating the content as HTML at carriage returns instead of the closing HTML tag.
`;

### Expected behavior

markdown parsing should resume from the closing </div> tag (or whatever the HTML element is)

### Actual behavior

It continues to treat the content as HTML, no longer parsing the markdown, until the next double carriage return \n\n

### Runtime

Node v17

### Package manager

yarn 3

### OS

Windows

### Build and bundle tools

Create React App

**Comment by wooorm** [comment]
Your markdown does not look good here. Please format correctly, use code blocks for code
