### ISSUE TITLE
parse5 console warn

### ISSUE THREAD

**Issue by BlackRam-oss** [rehypejs/rehype-raw#33]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.0.0

### Steps to reproduce

when the application starts it gives the following warn:
```
ENOENT: no such file or directory, open '/home/simone/template/pixi-vn-react-template/node_modules/parse5/dist/common/unicode.js.map'
```

### Expected behavior

there should be no warns

### Actual behavior

when the application starts it gives the following warn:
```
ENOENT: no such file or directory, open '/home/simone/template/pixi-vn-react-template/node_modules/parse5/dist/common/unicode.js.map'
```

### Build and bundle tools

Vite

**Comment by remcohaszing** [comment]
This is an issue in `parse5`.
