### ISSUE TITLE
InvalidCharacterError: Failed to execute 'createElement'

### ISSUE THREAD

**Issue by bradmsmith** [rehypejs/rehype-raw#34]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

Latest

### Steps to reproduce

1. Visit demo site: https://remarkjs.github.io/react-markdown/
2. Delete demo text and replace with `</p><</div>/span>/div><button&#160;onClick=alert(1)>`
3. Select the `Use rehype-raw` checkbox
4. View error in Developer Tools Javascript Console

### Expected behavior

Properly filter out malformed HTML tags and ASCII encoding of space (&amp;#160;)

### Actual behavior

Attempts to create a HTML element named <button&>

Note: if this is a bug in a dependency, I would appreciate if you could direct me to proper place to report issue. Posting it here because it only occurs when the `rehypeRaw` plugin is enabled for `react-markdown`.

### OS

macOS

**Comment by wooorm** [comment]
As mentioned, I do not think there is an alternative, this is how HTML and the DOM work
